FROM node:alpine as npminstall
WORKDIR /home/node/app
COPY package.json /home/node/app/
RUN npm install --silent
COPY . /home/node/app/
RUN npm run build

FROM sebp/lighttpd
# Adds correct timezone for access.log dates
RUN apk add tzdata && \
    cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime && \
    echo "Europe/Berlin" > /etc/timezone && \
    apk del tzdata

COPY --from=npminstall /home/node/app/_site/ /var/www/localhost/htdocs

EXPOSE 80
